### ISSUE TITLE
Parsing a quoted string should fail but does not

### ISSUE THREAD

**Issue by crule42** [mity/centijson#7]
Using the latest version as of 3 Dec 2020. 

I put the entire test suite at http://www.json.org/JSON_checker/ into the parser. All worked except for fail1.json which consist of a single line of quoted text.

    "A JSON payload should be an object or array, not a string."

It passes with no errors but should have failed.
[fail1.txt](https://github.com/mity/centijson/files/5638839/fail1.txt)

**Comment by mity** [comment]
I believe this is not a bug. Older RFC documents describing JSON format allowed only object or array as a root. Newer one allow **any** JSON value, including a string.

For more details, see the comment in the test suite here: https://github.com/mity/centijson/blob/7b9618a253c9e024babc02a8f9829236f673fc7e/tests/test-json.c#L1157-L1172

You should be able to enforce the old behavior with the flag `JSON_NOSCALARROOT`.

**Comment by crule42** [comment]
After reviewing what you said I agree with you. I had misunderstood the BNF at https://json.org. Thanks for the response.
